### ISSUE TITLE
Empty meshes

### ISSUE THREAD

**Issue by EnzoSigma** [galou/freecad.workbench_ros#4]
This file generate empty meshes for fusion part.
Rename attachment to `Bug_1.FCStd` 
[Bug_1.zip](https://github.com/galou/freecad.workbench_ros/files/11088466/Bug_1.zip)

**Comment by galou** [comment]
Should be solved with https://github.com/galou/freecad.workbench_ros/commit/d4596d70fa2471ae516819f07efefb0bce001616.
